#ifndef _MARK_H
#define _MARK_H


//for ip_mark;
#define IP_MARK_BASE		128

#define IP_MARK_SO_SET_ISPMEM	IP_MARK_BASE+1
#define IP_MARK_SO_SET_VALID	IP_MARK_BASE+2
#define IP_MARK_SO_SET_INVALID	IP_MARK_BASE+3
#define IP_MARK_SO_SET_CHECK	IP_MARK_BASE+4
#define IP_MARK_SO_SET_START	IP_MARK_BASE+5
#define IP_MARK_SO_SET_STOP	IP_MARK_BASE+6
#define IP_MARK_SO_SET_MAX	IP_MARK_SO_SET_STOP

#define IP_MARK_SO_GET_MARK	IP_MARK_BASE+1
#define IP_MARK_SO_GET_MAX	IP_MARK_SO_GET_MARK





#endif	/* _MARK_H */
